Adjust etcd formula to patch the python-etcd module
herisanu/etcd-formula pull request #3
Opened 2016-12-22 14:07 UTC by dpetre

- added state for optionally patching the etcd_client python module, in order for it to be compatible with etcd > v 3.

2016-12-22 14:08 UTC, dpetre commented
@herisanu can you please review this?

2016-12-22 16:40 UTC, herisanu requested changes
- could you please change the name of the patch file to etcd_client_ssl_tlsv12.patch
- could you please attach proof it works by showing a etcd sdb backed connection working over SSL

2016-12-22 16:40 UTC, herisanu commented on etcd/files/etcd_client_patch
> +--- /usr/lib/python2.7/site-packages/etcd/client.py	2016-12-22 13:41:54.913585308 +0000
could you please name this file as etcd_client_ssl_tlsv12.patch

2016-12-22 16:44 UTC, herisanu commented
The reason for this PR is that out-of-the-box the python-etcd client will not work with etcd v3 using SSL.
It throws an exception that TLS v1 is not supported and there is no option to use another protocol.

2016-12-22 16:48 UTC, herisanu commented
Hmm @dpetre I see this got addressed here:
https://github.com/jplana/python-etcd/commit/80f936963773053c36ebdff5185147b5e127f94d

Makes me wonder if it would be better to intstall the python dependency from the git url directly

2017-01-03 09:38 UTC, dpetre commented
@herisanu I looked into how we could install the `python-etcd` python module from the revision you mentioned (that fixes the TLS issue) and while pip allows you to specify a commit hash, I couldn't find this option for the `pip_state` state in Salt (maybe I'm missing out something)

2017-02-07 18:00 UTC, herisanu commented
This works with the latest version in git (python-etcd). Closing this out.

2017-02-07 18:00 UTC, closed without merging